# Generated by Django 5.2.15 on 2026-06-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todolist_todoitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='asignee',
            new_name='assignee',
        ),
    ]
