# Generated by Django 5.2.15 on 2026-06-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_todoitem_assignee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='parentList',
            new_name='parent_list',
        ),
    ]
